name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 1 * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1.10.0
      with:
        username: flohsg
        password: ${{ secrets.DOCKER_DEPLOY_KEY }}
        logout: true
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nginx_proxy_http:$(date +%s) -t nginx_proxy_http:latest && docker push nginx_proxy_http
